*> This is free-form
IDENTIFICATION DIVISION.
PROGRAM-ID. HELLO.
ENVIRONMENT DIVISION.
DATA DIVISION.
PROCEDURE DIVISION.
    DISPLAY "Hello from GNU Cobol in Docker + VS Code!".
    DISPLAY "Trevor Flahardy"
    STOP RUN.
